"""
Generate gdextension file dynamically.

Scans plugin/bin/ directory for built libraries and generates the
gdai.gdextension file with only the entries for libraries that exist.
"""

from pathlib import Path
from typing import Dict, Any, List, Tuple

from tools.base_tool import BaseTool


class GenerateGDExtensionTool(BaseTool):
    """Generate gdai.gdextension file based on built libraries."""
    
    @property
    def name(self) -> str:
        return "generate-gdextension"
    
    @property
    def description(self) -> str:
        return "Generate gdai.gdextension file from built libraries"
    
    @property
    def category(self) -> str:
        return "build"
    
    @property
    def visible(self) -> bool:
        return False  # Called by build-plugin automatically
    
    def execute(self, args: Dict[str, Any]) -> int:
        """Execute the generate-gdextension tool."""
        root_dir = self.get_root_dir()
        plugin_dir = root_dir / "plugin"
        bin_dir = plugin_dir / "bin"
        
        print("\n" + "=" * 70)
        print("Generating gdai.gdextension")
        print("=" * 70)
        
        # Scan for built libraries
        libraries = self._scan_libraries(bin_dir)
        
        if not libraries:
            self.print_warning("No libraries found in plugin/bin/")
            print("\nExpected structure:")
            print("  plugin/bin/<platform>/libgdai.<platform>.editor.<arch>.<ext>")
            return 1
        
        # Generate the gdextension file
        gdextension_path = plugin_dir / "gdai.gdextension"
        if not self._generate_file(gdextension_path, libraries):
            return 1
        
        # Show summary
        print("\n📄 Generated gdai.gdextension with entries for:")
        for platform, arch, _ in libraries:
            print(f"  - {platform}.editor.{arch}")
        
        print(f"\n✓ Saved to: {gdextension_path}")
        
        return 0
    
    def _scan_libraries(self, bin_dir: Path) -> List[Tuple[str, str, Path]]:
        """
        Scan bin directory for libraries.
        
        Args:
            bin_dir: plugin/bin directory
            
        Returns:
            List of (platform, architecture, filepath) tuples
        """
        libraries = []
        
        if not bin_dir.exists():
            return libraries
        
        # Platform-specific library patterns
        platform_patterns = {
            "windows": {"ext": ".dll", "prefix": "lib"},
            "linux": {"ext": ".so", "prefix": "lib"},
            "macos": {"ext": ".dylib", "prefix": "lib"},
        }
        
        # Scan platform directories
        for platform_dir in bin_dir.iterdir():
            if not platform_dir.is_dir():
                continue
            
            platform = platform_dir.name
            
            if platform not in platform_patterns:
                print(f"⚠️  Unknown platform directory: {platform}")
                continue
            
            pattern = platform_patterns[platform]
            
            # Find libraries in this platform directory
            for lib_file in platform_dir.glob(f"{pattern['prefix']}gdai.*{pattern['ext']}"):
                # Parse library filename to extract architecture
                # Expected format: libgdai.<platform>.editor.<arch>.<ext>
                # Example: libgdai.windows.editor.x86_64.dll
                
                parts = lib_file.stem.split(".")
                # parts = ['libgdai', 'windows', 'editor', 'x86_64']
                
                if len(parts) >= 4 and parts[2] == "editor":
                    arch = parts[3]
                    libraries.append((platform, arch, lib_file))
                else:
                    print(f"⚠️  Unexpected library name format: {lib_file.name}")
        
        return sorted(libraries)
    
    def _generate_file(self, output_path: Path, libraries: List[Tuple[str, str, Path]]) -> bool:
        """
        Generate the gdextension file.
        
        Args:
            output_path: Path to gdai.gdextension
            libraries: List of (platform, arch, filepath) tuples
            
        Returns:
            True if successful
        """
        try:
            content = [
                "[configuration]",
                'entry_symbol = "gdai_library_init"',
                'compatibility_minimum = "4.4"',
                'reloadable = true',
                "",
                "[libraries]",
                "# Auto-generated by generate-gdextension tool",
                "# DO NOT EDIT MANUALLY - this file is regenerated during build",
                ""
            ]
            
            # Group by platform
            by_platform = {}
            for platform, arch, filepath in libraries:
                if platform not in by_platform:
                    by_platform[platform] = []
                by_platform[platform].append((arch, filepath))
            
            # Generate entries for each platform
            for platform in sorted(by_platform.keys()):
                content.append(f"# {platform.capitalize()}")
                
                for arch, filepath in sorted(by_platform[platform]):
                    # Generate the path relative to res://addons/gdai/
                    # filepath is absolute, convert to relative from plugin/
                    rel_path = filepath.relative_to(output_path.parent)
                    godot_path = f"res://addons/gdai/{rel_path.as_posix()}"
                    
                    # Determine the key
                    if platform == "macos" and arch == "universal":
                        key = f"{platform}.editor"
                    else:
                        key = f"{platform}.editor.{arch}"
                    
                    content.append(f'{key} = "{godot_path}"')
                
                content.append("")
            
            # Write the file
            output_path.write_text("\n".join(content), encoding="utf-8")
            
            return True
            
        except Exception as e:
            self.print_error(f"Failed to generate gdextension file: {e}")
            import traceback
            traceback.print_exc()
            return False
    
    def generate_for_ci(self, platforms: List[str] = None) -> int:
        """
        Generate gdextension file for CI builds.
        
        This variant includes entries for all specified platforms,
        even if the libraries don't exist locally yet.
        
        Args:
            platforms: List of platforms to include (None = all)
            
        Returns:
            Exit code
        """
        root_dir = self.get_root_dir()
        plugin_dir = root_dir / "plugin"
        gdextension_path = plugin_dir / "gdai.gdextension"
        
        if platforms is None:
            platforms = ["windows", "linux", "macos"]
        
        print(f"\n📄 Generating CI gdextension template for: {', '.join(platforms)}")
        
        content = [
            "[configuration]",
            'entry_symbol = "gdai_library_init"',
            'compatibility_minimum = "4.4"',
            'reloadable = true',
            "",
            "[libraries]",
            "# Auto-generated for CI builds",
            "# This includes all platforms that will be built by GitHub Actions",
            ""
        ]
        
        # Platform-specific architectures
        platform_archs = {
            "windows": ["x86_64", "x86_32", "arm64"],
            "linux": ["x86_64", "x86_32", "arm64", "rv64"],
            "macos": ["universal", "x86_64", "arm64"]
        }
        
        for platform in platforms:
            content.append(f"# {platform.capitalize()}")
            
            archs = platform_archs.get(platform, ["x86_64"])
            
            for arch in archs:
                # Determine extension
                if platform == "windows":
                    ext = "dll"
                elif platform == "linux":
                    ext = "so"
                else:
                    ext = "dylib"
                
                # Generate path
                lib_name = f"libgdai.{platform}.editor.{arch}.{ext}"
                godot_path = f"res://addons/gdai/bin/{platform}/{lib_name}"
                
                # Determine key
                if platform == "macos" and arch == "universal":
                    key = f"{platform}.editor"
                else:
                    key = f"{platform}.editor.{arch}"
                
                content.append(f'{key} = "{godot_path}"')
            
            content.append("")
        
        try:
            gdextension_path.write_text("\n".join(content), encoding="utf-8")
            print(f"✓ Generated: {gdextension_path}")
            return 0
        except Exception as e:
            self.print_error(f"Failed to generate CI template: {e}")
            return 1